plugins {
    id 'java-library'
    id 'com.vanniktech.maven.publish' version '0.30.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

group = rootProject.group
version = rootProject.version

mavenPublishing {
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)
    signAllPublications()

    coordinates(group.toString(), 'pillar-api', version.toString())

    pom {
        name = 'Pillar API'
        description = 'Control-plane routing and lease platform for Minecraft (Paper/Velocity)'
        url = 'https://github.com/vinicius-paraujo/Pillar'
        licenses {
            license {
                name = 'The Apache License, Version 2.0'
                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
            }
        }
        developers {
            developer {
                id = 'markineo'
                name = 'Markineo'
                url = 'https://github.com/vinicius-paraujo'
            }
        }
        scm {
            connection = 'scm:git:git://github.com/vinicius-paraujo/Pillar.git'
            developerConnection = 'scm:git:ssh://github.com/vinicius-paraujo/Pillar.git'
            url = 'https://github.com/vinicius-paraujo/Pillar'
        }
    }
}

