plugins {
    id 'java-library'
    id 'maven-publish'
    id 'signing'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
}

group = rootProject.group
version = rootProject.version

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            pom {
                name = 'Pillar API'
                description = 'Control-plane routing and lease platform for Minecraft (Paper/Velocity)'
                url = 'https://github.com/markineo/Pillar'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'markineo'
                        name = 'Markineo'
                        email = 'dev@markineo.com.br'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/markineo/Pillar.git'
                    developerConnection = 'scm:git:ssh://github.com/markineo/Pillar.git'
                    url = 'https://github.com/markineo/Pillar'
                }
            }
        }
    }
    repositories {
        maven {
            name = "OSSRH"
            def releasesRepoUrl = "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            def snapshotsRepoUrl = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            url = version.toString().endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username = System.getenv("OSSRH_USERNAME")
                password = System.getenv("OSSRH_PASSWORD")
            }
        }
    }
}

signing {
    def signingKey = System.getenv("SIGNING_KEY")
    def signingPassword = System.getenv("SIGNING_PASSWORD")
    if (signingKey != null) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign publishing.publications.mavenJava
    }
}
